export const LOADLIST = 'LOADLIST';
export const LOADLIST_SUCCESS = 'LOADLIST_SUCCESS';
export const LOADLIST_FAILURE = 'LOADLIST_FAILURE';

export const SELECTLIST = 'SELECTLIST';

export const REALTIME_SAVING = 'REALTIME_SAVING';
export const REALTIME_SAVED = 'REALTIME_SAVED';
export const REALTIME_SAVE_ERROR = 'REALTIME_SAVE_ERROR';
