export const LOADLIST = 'LOADLIST';
export const LOADLIST_SUCCESS = 'LOADLIST_SUCCESS';
export const LOADLIST_FAILURE = 'LOADLIST_FAILURE';

export const SELECTLIST = 'SELECTLIST';

// export const REALTIME_SAVING = 'REALTIME_SAVING';
// export const REALTIME_SAVED = 'REALTIME_SAVED';
// export const REALTIME_SAVE_ERROR = 'REALTIME_SAVE_ERROR';

export const DELETE_ROWS = 'DELETE_ROWS';
export const DELETE_ROWS_SUCCESS = 'DELETE_ROWS_SUCCESS';
export const DELETE_ROWS_FAILURE = 'DELETE_ROWS_FAILURE';

export const LOADLISTDETAILS = 'LOADLISTDETAILS';
export const LOADLISTDETAILS_SUCCESS  = 'LOADLISTDETAILS_SUCCESS';
export const LOADLISTDETAILS_FAILURE  = 'LOADLISTDETAILS_FAILURE';

export const CREATELISTITEM = 'CREATELISTITEM';
export const CREATELISTITEM_SUCCESS  = 'CREATELISTITEM_SUCCESS';
export const CREATELISTITEM_FAILURE  = 'CREATELISTITEM_FAILURE';
