export const LOAD_COUNTS = 'app/Home/LOAD_COUNTS';
export const COUNTS_LOADING_SUCCESS = 'app/Home/COUNTS_LOADING_SUCCESS';
export const COUNTS_LOADING_ERROR = 'app/Home/COUNTS_LOADING_ERROR';


export const LOAD_GENDER_STATISTIC = 'app/Home/LOAD_GENDER_STATISTIC';
export const LOAD_GENDER_STATISTIC_SUCCESS = 'app/Home/LOAD_GENDER_STATISTIC_SUCCESS';
export const LOAD_GENDER_STATISTIC_ERROR = 'app/Home/LOAD_GENDER_STATISTIC_ERROR';

export const LOAD_JOIN_STATISTIC = 'app/Home/LOAD_JOIN_STATISTIC';
export const LOAD_JOIN_STATISTIC_SUCCESS = 'app/Home/LOAD_JOIN_STATISTIC_SUCCESS';
export const LOAD_JOIN_STATISTIC_ERROR = 'app/Home/LOAD_JOIN_STATISTIC_ERROR';
