export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPDATEPROFILELANG = 'UPDATEPROFILELANG';
export const UPDATEPROFILELANG_SUCCESS = 'UPDATEPROFILELANG_SUCCESS';
export const UPDATEPROFILELANG_FAILURE = 'UPDATEPROFILELANG_FAILURE';

// export const GETSESSION = 'GETSESSION';
// export const GETSESSION_SUCCESS = 'GETSESSION_SUCCESS';
// export const GETSESSION_FAILURE = 'GETSESSION_FAILURE';

// export const REFRESHSESSION = 'REFRESHSESSION';
// export const REFRESHSESSION_SUCCESS = 'REFRESHSESSION_SUCCESS';
// export const REFRESHSESSION_FAILURE = 'REFRESHSESSION_FAILURE';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const INITIAL_LIST = 'INITIAL_LIST';
